### ISSUE TITLE
Can't cast to subclass of generic types

### ISSUE THREAD

**Issue by cdchambers** [Saltarelle/SaltarelleCompiler#385]
I have the following in C#

```cs
class K
{
}

class A<T> where T : K
{
}

class B<T> : A<T> where T : K
{
}

class C : B<K>
{
}

A<K> b = new C();
```

Expected: b is B<K> to be `true`.
Actual: it is `false`.

I put the compiled javascript of the above into a fiddle, see http://jsfiddle.net/tha95xmx/4/

**Comment by erik-kallen** [comment]
Seems like a bug.

**Comment by erik-kallen** [comment]
This one was tricky. The problem is that the ```__assembly``` member of ```K``` is not assigned when the generic instantiation is created, which causes the name to be reported without assembly, which causes a different name to be registered for the generic type during inheritance resolution. Then, when the type test is actually performed, the ```__assembly``` member has been assigned.

**Comment by geoffreymcgill** [comment]
Looks like this sample is returning the correct expected result when compiling with Bridge.

http://deck.net/3afe5dd92e3e9e89726781c10620e504

```cs
public class Program
{
    public static void Main()
    {
        A<K> b = new C();
        
        // Should be true
        Console.WriteLine(b is B<K>);
    }
}

class K { }

class A<T> where T : K { }

class B<T> : A<T> where T : K { }

class C : B<K> { }
```

Hope this helps.
